[package]
name = "loptos"
version = "0.1.0"
authors = ["Martin Habovstiak <martin.habovstiak@gmail.com>"]
edition = "2018"

[package.metadata.configure_me]
spec = "config_spec.toml"

[features]
test_paths = []

[dependencies]
bitcoin = { version = "0.27.0", features = ["use-serde"] }
hyper = "0.14.9"
tonic_lnd = "0.2.1"
tokio = { version = "1.7.1", features = ["rt-multi-thread"] }
rand = "0.8.4"
base64 = "0.13.0"
serde = "1.0.126"
serde_json = "1.0.64"
serde_derive = "1.0.126"
ln-types = { version = "0.1.2", features = ["serde", "parse_arg"] }
configure_me = "0.4.0"

[build-dependencies]
configure_me_codegen = "0.4.1"
